g++ -std=c++11 exato.cpp -o exato -O3
./exato Instâncias/chr12a.dat
./exato Instâncias/chr15a.dat
./exato Instâncias/chr20a.dat
./exato Instâncias/chr25a.dat
./exato Instâncias/esc16a.dat
./exato Instâncias/esc32a.dat
./exato Instâncias/esc64a.dat
./exato Instâncias/had16.dat
./exato Instâncias/had20.dat
./exato Instâncias/kra32.dat
./exato Instâncias/nug27.dat
./exato Instâncias/nug28.dat
./exato Instâncias/rou12.dat
./exato Instâncias/rou15.dat
./exato Instâncias/rou20.dat
./exato Instâncias/scr12.dat
./exato Instâncias/scr15.dat
./exato Instâncias/scr20.dat
./exato Instâncias/tai12a.dat
./exato Instâncias/tai12b.dat
./exato Instâncias/tai15a.dat
./exato Instâncias/tai15b.dat
./exato Instâncias/tai17a.dat
./exato Instâncias/tai20a.dat
./exato Instâncias/tai20b.dat
./exato Instâncias/tai25a.dat
./exato Instâncias/tai25b.dat
./exato Instâncias/tai30a.dat
./exato Instâncias/tai30b.dat
./exato Instâncias/tai35a.dat